07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Models/Cela.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.Models
{
    public class Cela
    {
        public int CelaId { get; set; }
        public string Nome { get; set; }
        public float Area { get; set; }
        public int QuantidadeMaxima { get; set; }

        //Relacionamento
        public IList<Presidiario> Presidiarios { get; set; }
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _07_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Models/NivelEscolaridade.cs
namespace _07_Fiap.Web.AspNet.Models
{
    public enum NivelEscolaridade
    {
        Primario, Medio, Especialista, Superior, Mestrado, Doutorado
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Models/Presidiario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.Models
{
    public class Presidiario
    {
        public int PresidiarioId { get; set; }
        public string Nome { get; set; }
        public DateTime DataEntrada { get; set; }
        public DateTime DataSaida { get; set; }
        public NivelEscolaridade NivelEscolaridade { get; set; }
        public bool SaidaTemporaria { get; set; }

        //RELACIONAMENTO
        public Cela Cela { get; set; }
        public int CelaId { get; set; }
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/ViewModels/DetalheCelaViewModel.cs
using _07_Fiap.Web.AspNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.ViewModels
{
    public class DetalheCelaViewModel
    {
        public Cela Cela { get; set; }
        public IList<Presidiario> Presidiarios { get; set; }
        public float Ocupacao { get; set; }
        public int QuantidadePresidiarios { get; set; }
      
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Controllers/CelaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _07_Fiap.Web.AspNet.Models;
using _07_Fiap.Web.AspNet.Persistence;
using _07_Fiap.Web.AspNet.Repositories;
using _07_Fiap.Web.AspNet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class CelaController : Controller
    {

        private ICelaRepository _repository;
        private IPresidiarioRepository _presidiarioRepository;
        public CelaController(ICelaRepository repository, IPresidiarioRepository presidiarioRepository)
        {
            _repository = repository;
            _presidiarioRepository = presidiarioRepository;
        }


        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Cela cela)
        {
            _repository.Cadastrar(cela);
            _repository.Salvar();
            TempData["msg"] = "Cadastrado!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Listar()
        {
            return View(_repository.Listar());
        }

        [HttpGet]
        public IActionResult Detalhar(int codigo)
        {
            //Pesquisar a cela
            var cela = _repository.BuscarPorCodigo(codigo);
            //Listar os presidiários
            var presidiarios = _presidiarioRepository.BuscarPor(p => p.CelaId == codigo);

            //objeto que possui todas as informações da tela
            var viewModel = new DetalheCelaViewModel()
            {
                Cela = cela,
                Presidiarios = presidiarios,
                QuantidadePresidiarios = presidiarios.Count,
                Ocupacao = (presidiarios.Count * 100) / cela.QuantidadeMaxima
            };
            return View(viewModel);
        }
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _07_Fiap.Web.AspNet.Models;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Controllers/PresidiarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _07_Fiap.Web.AspNet.Models;
using _07_Fiap.Web.AspNet.Persistence;
using _07_Fiap.Web.AspNet.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class PresidiarioController : Controller
    {
        private IPresidiarioRepository _repository;
        private ICelaRepository _celaRepository;

        public PresidiarioController(IPresidiarioRepository repository, ICelaRepository celaRepository)
        {
            _repository = repository;
            _celaRepository = celaRepository;
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            var lista = _celaRepository.Listar();
            ViewBag.celas = new SelectList(lista, "CelaId", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Presidiario presidiario)
        {
            _repository.Cadastrar(presidiario);
            _repository.Salvar();
            TempData["msg"] = "Cadastrado";
            return RedirectToAction("Listar");
        }
    }
}

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Views/Cela/Cadastrar.cshtml
@model  Cela
@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar Cela</h1>

<form asp-action="cadastrar">
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Area"></label>
        <input asp-for="Area" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="QuantidadeMaxima"></label>
        <input asp-for="QuantidadeMaxima" class="form-control" />
    </div>

    <input type="submit" value="Cadastrar" class="btn btn-primary"/>
</form>

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Views/Cela/Detalhar.cshtml
@model  DetalheCelaViewModel

@{
    ViewData["Title"] = "Detalhar";
}

<h1>Detalhar</h1>

07-Fiap.Web.AspNet/07-Fiap.Web.AspNet/Views/Cela/Listar.cshtml
@model  IList<Cela>

@{
    ViewData["Title"] = "Listar";
}

<h2>Listar Celas</h2>

<a asp-action="Cadastrar" asp-controller="Cela">Cadastrar</a>
<br />
<message mensagem="@TempData["msg"]"></message>

<form asp-action="pesquisar" method="get" class="form-inline">
    <input placeholder="Digite o nome" type="text" name="termoPesquisa" class="form-control" />
    <input type="submit" value="Buscar" class="ml-2 btn btn-success" />
</form>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Área</th>
        <th>Quantidade Máxima</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Area</td>
            <td>@item.QuantidadeMaxima</td>
            <td>
                <a asp-action="detalhar" asp-route-id="@item.CelaId">Detalhes</a>
                <button onclick="codigo.value = @item.CelaId" type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#modalExemplo">
                    Remover
                </button>
            </td>
        </tr>
    }
</table>

<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente excluir?
            </div>
            <div class="modal-footer">
                <form asp-action="excluir">
                    <input type="hidden" name="id" id="codigo" />
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>