04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _04_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Models/Time.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _04_Fiap.Web.AspNet.Models
{
    public class Time
    {
        public string Nome { get; set; }
        public bool Classificado { get; set; }
        public int Vitorias { get; set; }

        [Display(Name="Data de Fundação")]
        [DataType(DataType.Date)]
        public DateTime DataFundacao { get; set; }

        [Display(Name = "Folha de Pagamento")]
        public decimal FolhaPagamento { get; set; }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _04_Fiap.Web.AspNet.Models;

namespace _04_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _04_Fiap.Web.AspNet.Models;
using System.Collections;

namespace _04_Fiap.Web.AspNet.Controllers
{
    public class TimeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private static IList _lista = new List<Time>();

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

       [HttpPost]
       public IActionResult Cadastrar(Time time)
        {
            
            //cadastrar time no banco simulado
            _lista.Add(time);
            
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Listar()
        {
            TempData["msg"] = "Time cadastrado com sucesso!";
            return View(_lista);
        }
    }
}

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Views/Time/Cadastrar.cshtml
@model Time;


@{
    ViewData["Title"] = "Cadastrar";
}



<h1>Cadastrar Time</h1>

<hr />

<h2>@TempData["msg"]</h2>

<div class="card">
    <div class="card-body">
        <form asp-action="Cadastrar" asp-controller="Time">
            <div class="form-group">
                <label asp-for="Nome">Nome</label>
                <input asp-for="Nome" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="DataFundacao">Data de fundação</label>
                <input asp-for="DataFundacao" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="FolhaPagamento">Folha de Pagamento</label>
                <input asp-for="FolhaPagamento" class="form-control" />
            </div>

            <div class="form-group">
                <input asp-for="Classificado" />
                <label asp-for="Classificado">Classificado</label>
            </div>

            <div class="form-group">
                <label asp-for="Vitorias">Vitórias</label>
                <input asp-for="Vitorias" class="form-control" />
            </div>
            <br />
            <input type="submit" value="Cadastrar" class="btn btn-primary" />
            <br />
            <a asp-controller="Time" asp-action="Listar" class="btn btn-primary mt-4">Listar</a>
        </form>
    </div>
</div>

04-Fiap.Web.AspNet/04-Fiap.Web.AspNet/Views/Time/Listar.cshtml
@model  List<Time>
    
    @{
        ViewData["Title"] = "Listar";
    }

@if (TempData["msg"] != null) {
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}
    <h1>Lista de Times</h1>
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data de Fundação</th>
                <th>Folha de Pagamento</th>
                <th>Classificado</th>
                <th>Vitórias</th>
            </tr>
            @foreach (var time in Model)
            {
                <tr>
                    <td>@time.Nome</td>
                    <td>@time.DataFundacao</td>
                    <td>@time.FolhaPagamento</td>
                    <td>@(time.Classificado?"Sim":"Não")</td>
                    <td>@time.Vitorias</td>
                </tr>
            }
        </thead>
    </table>
<br />
<a asp-controller="Time" asp-action="Cadastrar" class="btn btn-primary">Voltar</a>